### ISSUE TITLE
[BUG] Corrigir link de download de acidentes

### ISSUE THREAD

**Issue by nymarya** [nymarya/prf_api#10]
O portal de dados aberto alterou o link para download. A tarefa é alterar o link de download quando o download for referente a acidentes agrupados por ocorrência ( tipo `acidentes_ocorrencia`).

Novo formato de link:
![Screenshot from 2019-09-30 13-19-29](https://user-images.githubusercontent.com/23341788/65898369-ca8f7480-e387-11e9-9e25-da1d11c796ad.png)

### Edit 05/2021
O link já mudou novamente, o novo endereço é `https://portal.prf.gov.br/dados-abertos-acidentes`

> #### Participe do Hacktoberfest!
> Contribua com uma issue com a label `hacktoberfest` e abra um pull request durante o mês de outubro para ganhar os brindes do GitHub! Para se inscrever, acesse https://hacktoberfest.digitalocean.com/register

**Comment by SamuelsSantos** [comment]
@nymarya você está trabalhando nesta issue? Caso não esteja posso pegar?

**Comment by nymarya** [comment]
@SamuelsSantos não tem ninguém com essa issue, fique à vontade! :)

**Comment by SamuelsSantos** [comment]
@nymarya pode me associar a ela então.
